<?php

/**
 * @file
 * Install, update and uninstall functions for the userprotect module.
 */

/**
 * Implements hook_install().
 *
 * Installs default userprotect permissions for authenticated users.
 */
function userprotect_install() {
  $role = entity_load('user_role', DRUPAL_AUTHENTICATED_RID);
  $role->grantPermission('userprotect.mail.edit');
  $role->grantPermission('userprotect.pass.edit');
  $role->grantPermission('userprotect.account.edit');
  $role->save();
}
