<?php
/**
 * @file
 * Main module file containing hooks.
 */

use Drupal\simplesitemap\Simplesitemap;
use Drupal\simplesitemap\SitemapGenerator;

/**
 * Implements hook_form_alter.
 */
function simplesitemap_form_alter(&$form, $form_state, $form_id) {

  $form_entity = Simplesitemap::get_form_entity($form_state);
  if (!$form_entity)
    return;

  $entity_type_id = $form_entity->getEntityTypeId();
  if (!Simplesitemap::get_plugin_path($entity_type_id))
    return;

  $bundle_name = $form_entity->Id();

  $sitemap = new Simplesitemap;

  // Get current entity type sitemap settings.
  $entity_types = $sitemap->get_entity_types();

  $form['simplesitemap'] = array(
    '#group' => 'additional_settings',
    '#title' => t('Simple XML sitemap'),
    '#type' => 'details'
  );

  $index_content_checked = isset($entity_types[$entity_type_id][$bundle_name]['index']) ? $entity_types[$entity_type_id][$bundle_name]['index'] : FALSE;
  $form['simplesitemap']['simplesitemap_index_content'] = array(
    '#type' => 'checkbox',
    '#title' => t('Index content of this type'),
    '#default_value' => $index_content_checked,
  );

  $priority = isset($entity_types[$entity_type_id][$bundle_name]['priority']) ? $entity_types[$entity_type_id][$bundle_name]['priority'] : SitemapGenerator::PRIORITY_DEFAULT;
  $form['simplesitemap']['simplesitemap_priority'] = array(
    '#type' => 'select',
    '#title' => t('Priority'),
    '#description' => t('The priority entities of this bundle will have in the eyes of search engine bots.'),
    '#options' => SitemapGenerator::get_priority_select_values(),
    '#default_value' => $priority,
  );

  $form['simplesitemap']['simplesitemap_rebuild_now'] = array(
    '#type' => 'checkbox',
    '#title' => t('Rebuild sitemap after hitting Save'),
    '#description' => t('This setting will rebuild the whole sitemap including the above changes.<br/>Otherwise the sitemap will be rebuilt on next cron run.'),
    '#default_value' => FALSE,
  );

  // Add submission handler.
  $form['actions']['submit']['#submit'][] = 'simplesitemap_entity_form_submit';

}

/**
 * Form submission handler called in hook_form_alter.
 *
 * todo: use $form_state->getValue() instead $form array
 */
function simplesitemap_entity_form_submit($form, &$form_state) {

  $sitemap = new Simplesitemap;

  // Only make changes in DB if sitemap settings actually changed.
  if ($form['simplesitemap']['simplesitemap_index_content']['#default_value'] != $form['simplesitemap']['simplesitemap_index_content']['#value'] || $form['simplesitemap']['simplesitemap_priority']['#default_value'] != $form['simplesitemap']['simplesitemap_priority']['#value']) {

    $form_entity = Simplesitemap::get_form_entity($form_state);
    $entity_type_id = $form_entity->getEntityTypeId();
    $bundle_name = $form_entity->Id();

    // Get current entity type sitemap settings.
    $entity_types = $sitemap->get_entity_types();

    $values = $form_state->getValues();
    $entity_types[$entity_type_id][$bundle_name]['index'] = $values['simplesitemap_index_content'];
    $entity_types[$entity_type_id][$bundle_name]['priority'] = $values['simplesitemap_priority'];

    // Save new entity type settings.
    $sitemap->save_entity_types($entity_types);
  }

  // Regenerate sitemaps according to user setting.
  if ($form['simplesitemap']['simplesitemap_rebuild_now']['#value']) {
    $sitemap->generate_sitemap();
  }
}

/**
 * Implements hook_cron.
 */
function simplesitemap_cron() {

  // Regenerate sitemaps for all languages and save them into strings for performance reasons (pseudo caching).
  $sitemap = new Simplesitemap;
  $sitemap->generate_sitemap();
}

/**
 * Implements hook_entity_bundle_delete().
 */
function simplesitemap_entity_bundle_delete($entity_type_id, $bundle) {
  $sitemap = new Simplesitemap;
  $entity_types = $sitemap->get_entity_types();
  $bundle_entity_type_id = \Drupal::entityManager()->getDefinition($entity_type_id)->getBundleEntityType();

  if (isset($entity_types[$bundle_entity_type_id][$bundle])) {
    unset($entity_types[$bundle_entity_type_id][$bundle]);
    $sitemap->save_entity_types($entity_types);
    drupal_set_message(t("You may want to <a href='@url'>rebuild</a> your XML sitemap now. Otherwise it will be rebuilt on the next cron run.", array('@url' => $GLOBALS['base_url'] . '/admin/config/search/simplesitemap')));

  }
}
